name: Platform Connectivity Preparation
description: Use it to prepare the needed config and secrets to connect to ECP platforms
author: k24 devops team

inputs:
  vpn_profile:
    description: 'ECP VPN profile'
    required: true
  platform_id:
    description: 'ECP Platform name'
    required: true
  kubeconfig:
    description: 'custom kubeconfig config file'
    required: true
  kubeconfig_raw:
    description: 'content of kubeconfig config file'
    required: false
  kubeconfig_base64:
    description: 'content of kubeconfig config file in base64 format'
    required: false
  helm_version:
    description: 'Helm binary version'
    required: true
  kubectl_version:
    description: 'kubectl binary version'
    required: true


runs:
  using: "composite"
  steps:
    - name: Setup Environment with VPN
      run: ${{ github.action_path }}/scripts/setup_env.sh
      shell: bash
      working-directory: ${{ runner.temp }}
      env:
        HELM_VERSION: ${{ inputs.helm_version }}
        KUBECTL_VERSION: ${{ inputs.kubectl_version }}
    - name: Prepare k8s connectivity
      run: ${{ github.action_path }}/scripts/connect_to_k8s.sh
      shell: bash
      env:
        VPN_PROFILE: ${{ inputs.vpn_profile }}
        PLATFORM_ID: ${{ inputs.platform_id }}
        KUBECONFIG: ${{ inputs.kubeconfig }}
        KUBECONFIG_RAW: ${{ inputs.kubeconfig_raw }}
        KUBECONFIG_BASE64: ${{ inputs.kubeconfig_base64 }}

branding:
  icon: 'tool'
  color: 'blue'
