name: Platform Connectivity Preparation
description: Use it to prepare the needed config and secrets to connect to ECP platforms
author: k24 devops team

inputs:
  vpn_profile:
    description: 'ECP VPN profile'
    required: true
  git_token:
    description: 'ECP Github Token'
    required: true
  platform_code_values_dir:
    description: 'Github Repo path of Platform-code'
    required: true
  platform_id:
    description: 'ECP Platform name'
    required: true
  kubeconfig:
    description: 'custom kubeconfig config file'
    required: true
  kubeconfig_raw:
    description: 'content of kubeconfig config file'
    required: false
  kubeconfig_base64:
    description: 'content of kubeconfig config file in base64 format'
    required: false
  platform_env:
    description: 'ECP AWS env'
    required: true
  helm_version:
    description: 'Helm binary version'
    required: true
  kubectl_version:
    description: 'kubectl binary version'
    required: true


runs:
  using: "composite"
  steps:
    - name: Setup Environment with VPN
      run: ${{ github.action_path }}/scripts/setup_env.sh
      shell: bash
      working-directory: ${{ runner.temp }}
    - name: Get Config and secrets files
      run: ${{ github.action_path }}/scripts/get_config_and_secrets.sh
      shell: bash
    - name: Prepare k8s connectivity
      run: ${{ github.action_path }}/scripts/connect_to_k8s.sh
      shell: bash

branding:
  icon: 'tool'
  color: 'blue'
